sfm: Fix unknown uint type error in mingw
uint is defined in sys/types.h in Linux for compatibility.
But it is not defined in Win32 platform. This fixes the following error:

opencv_contrib/modules/sfm/src/libmv_light/libmv/multiview/robust_estimation.h:59:8: error: 'uint' does not name a type; did you mean 'int'?
   59 | static uint IterationsRequired(int min_samples,
      |        ^~~~
      |        int